"""empty message

Revision ID: 0652d5b26c0a
Revises: 
Create Date: 2019-07-03 15:06:16.045986

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import table, column
from sqlalchemy import String, Integer, Date
from jdfbots.models import GUID
sa.GUID = GUID


# revision identifiers, used by Alembic.
revision = '0652d5b26c0a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('config',
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('group',
    sa.Column('id', sa.GUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('state', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.GUID(), autoincrement=False, nullable=False),
    sa.Column('first_name', sa.String(length=255), nullable=False),
    sa.Column('last_name', sa.String(length=255), nullable=False),
    sa.Column('gender', sa.String(length=255), nullable=False),
    sa.Column('locale', sa.String(length=255), nullable=False),
    sa.Column('timezone', sa.String(length=255), nullable=False),
    sa.Column('facebook_id', sa.BigInteger(), nullable=False),
    sa.Column('last_interaction', sa.DateTime(), nullable=False),
    sa.Column('state', sa.String(length=255), nullable=True),
    sa.Column('language', sa.String(length=3), nullable=True),
    sa.Column('gid', sa.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['gid'], ['group.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('facebook_id')
    )
    op.create_table('data',
    sa.Column('user', sa.GUID(), nullable=False),
    sa.Column('clz', sa.String(length=255), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user', 'clz')
    )
    op.create_table('log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user', sa.GUID(), nullable=False),
    sa.Column('direction', sa.String(length=1), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('time', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('log')
    op.drop_table('data')
    op.drop_table('user')
    op.drop_table('group')
    op.drop_table('config')
    # ### end Alembic commands ###


# Populate the data to the User

def populate():
    user = table('user')
    op.bulk_insert(user,
                   [
                       {'id': 'f7884761-43e9-45f0-a729-c05294210604',
                        'first_name': 'John',
                        'last_name': 'Doe',
                        'gender': 'SEX_M',
                        'locale':'',
                        'timezone': '',
                        'facebook_id': '',
                        'last_interaction': '',
                        'state': '',
                        'gid': ''
                        }
                   ])





