# Generated by Django 2.1.7 on 2019-07-09 07:54

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(blank=True, null=True)),
                ('user', models.UUIDField(default=uuid.uuid4)),
                ('clz', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, null=True)),
                ('state', models.CharField(default='recruitment', max_length=255)),
                ('created_date', models.DateTimeField(default=datetime.datetime.utcnow)),
            ],
            options={
                'db_table': 'group',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=255)),
                ('facebook_id', models.BigIntegerField(unique=True)),
                ('last_interaction', models.DateTimeField(default=datetime.datetime.utcnow)),
                ('state', models.CharField(default='language.Start', max_length=255)),
                ('language', models.CharField(max_length=3, null=True)),
                ('gid', models.ForeignKey(db_column='gid', on_delete=django.db.models.deletion.DO_NOTHING, to='app.Group')),
            ],
            options={
                'db_table': 'user',
                'managed': True,
            },
        ),
    ]
