# Generated by Django 2.1.7 on 2019-08-06 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190717_1147'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'managed': False},
        ),
    ]
