# Generated by Django 2.1.7 on 2019-08-07 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20190806_2217'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'managed': True},
        ),
    ]
