# Generated by Django 2.1.7 on 2019-08-07 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20190807_0924'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='data',
            options={'managed': True},
        ),
    ]
