# Generated by Django 2.1.7 on 2019-08-07 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20190807_1503'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='data',
            options={'managed': False},
        ),
    ]
